av_jobs:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | as_number }}"
      user: "{{ env_var('POSTGRES_USER', 'av_jobs') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', '') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'av_jobs') }}"
      schema: bronze
      threads: 2
