from __future__ import annotations

import argparse
import logging
from pathlib import Path

import yaml

from scrapers.service.llm.category_taxonomy import CategoryTaxonomyExtractor
from scrapers.service.llm.groq_client import GroqCompletion

logger = logging.getLogger(__name__)

DEFAULT_OUTPUT_PATH = Path("scrapers") / "config" / "category_main_types.yaml"


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    parser = argparse.ArgumentParser(
        description=(
            "One-time LLM call that proposes main_type groupings for the fixed "
            "9-category taxonomy. Review the output before committing it - this "
            "is a taxonomy design decision, applied to every job via a static "
            "mapping, not re-run per job."
        )
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args(argv)

    mapping = CategoryTaxonomyExtractor(GroqCompletion()).extract()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as stream:
        stream.write(
            "# Generated by: python -m scrapers.utils.extract_category_taxonomy\n"
            "# main_type is a property of the category (there is one Category row per\n"
            "# sub_type), not of any individual job - review this grouping before\n"
            "# relying on it, then keep it static rather than regenerating per run.\n"
        )
        yaml.safe_dump(mapping, stream, sort_keys=True, allow_unicode=True)

    for sub_type, main_type in sorted(mapping.items()):
        logger.info("%s -> %s", sub_type, main_type)
    logger.info("Wrote taxonomy mapping to %s.", args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
